settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Giovanni Gallo # [First Name(s)] [Last Name]
  links:
    - https://github.com/smokingred83/leetCode
    - https://github.com/smokingred83/code-generator
    - https://github.com/smokingred83/CS224n
